robotpy/robotpy-wpilib

wpilib/tests/test_builtinaccelerometer.py
wpilib/wpilib/adxl345_i2c.py
wpilib/wpilib/adxl345_spi.py
wpilib/wpilib/builtinaccelerometer.py
wpilib/wpilib/powerdistributionpanel.py

Implemented some upstream changes to LiveWindow objects.

---

wpilib/wpilib/counter.py
wpilib/wpilib/encoder.py

Implemented some upstream features.

---

hal-base/hal/exceptions.py
hal-base/hal/frccan.py
wpilib/wpilib/robotdrive.py

A couple of tweaks towards #48

Tweaks to RobotDrive, added CANNotInitializedException

---

wpilib/wpilib/canjaguar.py

Fixed some bugs stopping you from using the CAN Jaguars.

Fixes to CAN Jaguar.

---

wpilib/wpilib/canjaguar.py

More critical fixes to CAN Jaguar.

---

hal-base/hal/functions.py
hal-sim/hal_impl/data.py
hal-sim/hal_impl/functions.py
wpilib/tests/test_encoders.py
wpilib/wpilib/encoder.py

What version do we want to upgrade the HAL binary to?
Implements #121.

Add setEncoderIndexSource to Encoder

---

wpilib/wpilib/canjaguar.py

Added free() to CANJaguar, as is upstream.

Can jag free

---

examples/examples/GearsBot/subsystems/elevator.py

The proportional constant is passed to the first and second parameter and the integral constant is unused.

GearsBot Bug

---

hal-sim/hal_impl/data.py
wpilib/tests/test_hal_sim.py

This will make it possible for a simulator to update HAL wholesale without race conditions. I still need to test this more to make sure that this isn't an insane idea, but welcome comments on it.

Markup the hal_dict, and add a recursive update function

---

hal-base/hal/functions.py
hal-roborio/hal_impl/types.py
hal-roborio/setup.py
hal-sim/hal_impl/functions.py
hal-sim/hal_impl/types.py
wpilib/tests/spec_scanners/hal_scanner.py
wpilib/tests/spec_scanners/wpilib_scanner.py
wpilib/tests/test_driverstation.py
wpilib/wpilib/cameraserver.py
wpilib/wpilib/canjaguar.py
wpilib/wpilib/counter.py
wpilib/wpilib/driverstation.py
wpilib/wpilib/joystick.py
wpilib/wpilib/powerdistributionpanel.py
wpilib/wpilib/preferences.py
wpilib/wpilib/relay.py
wpilib/wpilib/resource.py
wpilib/wpilib/sensorbase.py
wpilib/wpilib/talon.py
wpilib/wpilib/victorsp.py

Working through the differences detected by `wpilib_scanner.py`, more to come.

Miscellaneous WPILIB updates for 2016

---

hal-base/hal/functions.py
hal-roborio/hal_impl/types.py
hal-roborio/setup.py
hal-sim/hal_impl/functions.py
hal-sim/hal_impl/types.py
wpilib/tests/spec_scanners/hal_scanner.py
wpilib/tests/test_driverstation.py
wpilib/wpilib/driverstation.py
wpilib/wpilib/powerdistributionpanel.py
wpilib/wpilib/sensorbase.py

This is not ready to merge yet, I just needed a place to discuss stuff with the group.
Also, feel free to double check any of my work.

Adjusting for upstream HAL API updates, needs more work.

---

installer/installer.py

Added commands for downloading and installing opkg files, updated architecture and repo link for 2016.

Various updates to installer.

---

wpilib/wpilib/command/command.py
wpilib/wpilib/command/commandgroup.py
wpilib/wpilib/command/pidcommand.py
wpilib/wpilib/command/pidsubsystem.py
wpilib/wpilib/command/printcommand.py
wpilib/wpilib/command/scheduler.py
wpilib/wpilib/command/startcommand.py
wpilib/wpilib/command/subsystem.py
wpilib/wpilib/command/waitcommand.py
wpilib/wpilib/command/waitforchildren.py
wpilib/wpilib/command/waituntilcommand.py

The only changes to the command java files where in PIDSubsystem.java and PIDCommand.java which was a change to the PIDSource source instance variable (which is not used in the python implementation) and Scheduler.java which had changes based on modifications to networktables which I was told we did not need to change in scheduler.py.

validated command files

---

hal-base/hal/constants.py
hal-sim/hal_impl/functions.py
wpilib/tests/test_cantalon.py
wpilib/wpilib/cantalon.py

* Add unit tests for CANTalon
* Some backwards-incompatible hal_data changes, but increases consistency and should be easier to use now
* Fixes #175
If you care about simulation with CANTalon, please review these changes and leave any comments here. Hopefully the breakage should be pretty small, but the benefits will be large. If I don't receive any responses in a day or so, I'll push a new release with this.

Update CANTalon for 2016

---

wpilib/wpilib/pidcontroller.py

Due to asynchronous calls to Timer.delay() it was possible for getDeltaSetpoint()
to throw a divide by zero error.
Cancelling the TimerTask thread outside the mutex avoids some deadlocks,
which may be the reason behind the testing hangs discussed in
robotpy/pyfrc#46
I have run my team's test code and the NavX example that cause the Travis failure repeatedly and they do not hang. I was able to intermittently get the hang before I made these changes.

Fix thread errors in PIDController.

---

installer/installer.py

Like the pyfrc one, this is untested, but I think it should work.

Fixed the IPv6 deploy problem with unpacking socket.getaddrinfo().

---

devtools/exclude_commits

Exclude upstream reformatting commits

---

docs/getting_started.rst
docs/guide/running.rst
hal-base/README.rst
hal-base/hal/main.py
installer/README-dist.txt
installer/installer.py
installer/installer.rst
wpilib/README.rst
wpilib/wpilib/_impl/main.py
wpilib/wpilib/builtinaccelerometer.py
wpilib/wpilib/controllerpower.py
wpilib/wpilib/preferences.py
wpilib/wpilib/utility.py

See wpilibsuite/allwpilib@7a402b4.

Replace "RoboRIO" with "roboRIO"

---

wpilib/wpilib/interfaces/generichid.py
wpilib/wpilib/interfaces/joystickbase.py
wpilib/wpilib/joystick.py

Also fixed a typo in GenericHID and validated it.

Update Joystick, add JoystickBase

---

wpilib/wpilib/geartooth.py
wpilib/wpilib/interfaces/gamepadbase.py

Just a couple of quick updates.

Write gamepadbase and validate geartooth

---

hal-base/hal/functions.py
hal-sim/hal_impl/functions.py
wpilib/wpilib/analoginput.py
wpilib/wpilib/analogoutput.py
wpilib/wpilib/gyrobase.py
wpilib/wpilib/interruptablesensorbase.py
wpilib/wpilib/relay.py
wpilib/wpilib/sensorbase.py

Update SensorBase, InterruptableSensorBase, and Relay.
Validate AnalogInput, AnalogOutput, and GyroBase.
Also define `hal.getSystemClockTicksPerMicrosecond()` for SensorBase.

SensorBase updates for 2017

---

wpilib/tests/test_utility.py
wpilib/wpilib/analoggyro.py
wpilib/wpilib/analoginput.py
wpilib/wpilib/analogpotentiometer.py
wpilib/wpilib/builtinaccelerometer.py
wpilib/wpilib/interruptablesensorbase.py
wpilib/wpilib/iterativerobot.py
wpilib/wpilib/lineardigitalfilter.py
wpilib/wpilib/robotbase.py
wpilib/wpilib/samplerobot.py

Trivial formatting changes upstream.
Checked HAL function names in python code.

Further updates to files for 2017

---

wpilib/wpilib/interruptablesensorbase.py

Fix InterruptableSensorBase

---

wpilib/tests/test_lineardigitalfilter.py
wpilib/wpilib/lineardigitalfilter.py

Implements all tests found in Java implementation.
Extra tests for 100% coverage.
Fixed issue where clearing deques.
Fixes #169

Unit tests for lineardigitalfilter.py

---

wpilib/wpilib/encoder.py

Most calls to get/set are now handled through HAL.

Updated encoder.py

---

hal-sim/hal_impl/data.py
hal-sim/hal_impl/functions.py
hal-sim/hal_impl/types.py
wpilib/tests/conftest.py
wpilib/tests/test_counter.py
wpilib/tests/test_driverstation.py
wpilib/tests/test_encoders.py
wpilib/tests/test_interfaces.py
wpilib/tests/test_relay.py
wpilib/wpilib/command/scheduler.py
wpilib/wpilib/driverstation.py
wpilib/wpilib/encoder.py
wpilib/wpilib/relay.py
wpilib/wpilib/sensorbase.py

Every unit test runs individually except test_driverstation.py.
There is still a resource locking issue when running all tests together.

Hal for tests

---

wpilib/wpilib/pidcontroller.py

PIDController: Fix argument handling and docs

---

hal-base/hal/functions.py
hal-sim/hal_impl/fndef.py
hal-sim/hal_impl/functions.py
hal-sim/hal_impl/serial_helpers.py
wpilib/tests/spec_scanners/hal_scanner.py
wpilib/tests/test_serial.py
wpilib/wpilib/__init__.py
wpilib/wpilib/serialport.py

I don't have hardware to test this on. @dangyogi can you test this and see if it works for you?
* Fixes #128

Add the WPILib SerialPort object

---

wpilib/wpilib/_impl/main.py

So I think this will work, but I'm not completely sure about the inner workings of wpilib to know if this is the right place to put this. 
I also don't know how to test for this, since it involves reporting to the DS

Report uncaught exceptions to DS

---

wpilib/wpilib/robotdrive.py

I'm gonna be updating this as I go. Would you like 1 PR per file/group of files or just as many as I can do before you merge?

Update robotdrive for 2018

---

hal-base/hal/constants.py
hal-sim/hal_impl/functions.py
wpilib/tests/test_pwm_motor_controllers.py
wpilib/wpilib/__init__.py
wpilib/wpilib/pwmtalonsrx.py

See wpilibsuite/allwpilib@ba3a85d0ccabccd32444d682b9713120371141b9.

Rename TalonSRX to PWMTalonSRX

---

wpilib/wpilib/robotbase.py

Also change this to use our NetworkTables global, which points to the
default NetworkTablesInstance.
As a bonus, also use type hints, to aid static analysis tools that don't
understand Sphinx type field directives.

Update RobotBase for 2018

---

wpilib/tests/conftest.py
wpilib/tests/test_pidcontroller.py
wpilib/wpilib/_impl/utils.py
wpilib/wpilib/pidcontroller.py

also, found why the new networktables impl was throwing null refs - the tests would sometimes free networktables first and then free the wpilib stuff.

add unit tests for pid controller

---

wpilib/tests/test_pidcontroller.py
wpilib/wpilib/pidcontroller.py

update pidcontroller for 2018 some more

---

hal-base/hal/constants.py
wpilib/tests/sim_hooks.py
wpilib/tests/test_nidecbrushless.py
wpilib/wpilib/__init__.py
wpilib/wpilib/nidecbrushless.py

hal is throwing a fit, not sure what the deal is

port NidecBrushless.java

---

wpilib/wpilib/digitalinput.py
wpilib/wpilib/digitaloutput.py
wpilib/wpilib/digitalsource.py

digitalinput
digitaloutput
interruptablesensorbase
digitalsource

Update digital files

---

.travis.yml
docs/requirements.txt

This should fix the bustage from #383.

Fix docs installation step

---

hal-base/hal/functions.py
hal-sim/hal_impl/functions.py
hal-sim/hal_impl/sim_hooks.py
hal-sim/hal_impl/types.py
wpilib/tests/test_notifier.py
wpilib/wpilib/__init__.py
wpilib/wpilib/notifier.py

- Note that pyfrc will require a special hook for this to work

Add Notifier

---

wpilib/tests/test_solenoid.py
wpilib/wpilib/adxrs450_gyro.py
wpilib/wpilib/analoggyro.py
wpilib/wpilib/doublesolenoid.py

Update Encoder, AnalogGyro, DoubleSolenoid, and ADXRS450_Gyro for the LiveWindow changes.

More Sendable updates

---

hal-base/hal/functions.py
hal-roborio/hal_impl/distutils.py
hal-sim/hal_impl/functions.py
hal-sim/hal_impl/spi_helpers.py
wpilib/tests/test_spi.py
wpilib/wpilib/__init__.py
wpilib/wpilib/accumulatorresult.py
wpilib/wpilib/adxrs450_gyro.py
wpilib/wpilib/analoginput.py
wpilib/wpilib/gyrobase.py
wpilib/wpilib/spi.py

I tested these on a RoboRIO before I left, so if the tests pass then I think they're fine unless there's something I accidentally included.

HAL + SPI updates

---

hal-sim/hal_impl/functions.py
wpilib/tests/test_robotcontroller.py
wpilib/tests/test_utility.py
wpilib/wpilib/utility.py

Update utility for 2018

---

wpilib/tests/test_analogaccelerometer.py
wpilib/tests/test_builtinaccelerometer.py
wpilib/tests/test_solenoid.py
wpilib/wpilib/adxl345_i2c.py
wpilib/wpilib/adxl345_spi.py
wpilib/wpilib/adxl362.py
wpilib/wpilib/analogaccelerometer.py
wpilib/wpilib/analogoutput.py
wpilib/wpilib/analogtrigger.py
wpilib/wpilib/analogtriggeroutput.py
wpilib/wpilib/builtinaccelerometer.py
wpilib/wpilib/buttons/trigger.py
wpilib/wpilib/digitalglitchfilter.py
wpilib/wpilib/sendable.py
wpilib/wpilib/sendablebuilder.py

Didn't touch i2c because it's too far from wpilibj for me
to do comfortably

Update livewindow changes

---

hal-sim/hal_impl/data.py
hal-sim/hal_impl/functions.py
hal-sim/hal_impl/mode_helpers.py

`getMatchTime()` should return the number of seconds remaining in the simulated match, not the number of seconds for which the match has been running.

Count sim timer down rather than up

---

.gittrack
devtools/exclude_commits

One last time maybe? I want to update #406 to this commit, so.

Bump gittrack

---

wpilib/tests/test_drive.py
wpilib/wpilib/drive/differentialdrive.py
wpilib/wpilib/drive/killoughdrive.py
wpilib/wpilib/drive/mecanumdrive.py
wpilib/wpilib/drive/robotdrivebase.py

* Fix the broken drive base diagrams.
* Put the RobotDrive porting guides in note directives for clarity.
* Add the missing code snippets in DifferentialDrive.
* [upstream change] Invert the right motor on LiveWindow in DifferentialDrive.

Update wpilib.drive and fix docs

---

hal-base/hal/functions.py
hal-roborio/hal_impl/fndef.py

Move errcheck to RETFUNC

---

hal-base/hal/functions.py
wpilib/tests/test_driverstation.py
wpilib/wpilib/driverstation.py

_This PR has been brought to you by the nursery rhyme "I'm a Little Teapot". The patch may be short and stout._
Fixes: #418

Fix getMatchInfo erroring on roboRIO

---

.gittrack
wpilib/tests/test_drive.py
wpilib/wpilib/drive/differentialdrive.py
wpilib/wpilib/robotdrive.py
wpilib/wpilib/speedcontrollergroup.py

Right side motors weren't being reversed in arcade or curvature drive.

Update drive. Urgent. 

---

wpilib/wpilib/buttons/joystickbutton.py
wpilib/wpilib/interfaces/gamepadbase.py
wpilib/wpilib/interfaces/generichid.py
wpilib/wpilib/joystick.py
wpilib/wpilib/xboxcontroller.py

Also add missing GenericHID.getButtonCount(), and use enum.IntEnum.

Add typing info to HID classes

---

hal-sim/hal_impl/types.py
wpilib/wpilib/driverstation.py

(why am I submitting PRs at 2am)

Update DriverStation for WPILib 2018.2.2

---

hal-base/hal/functions.py

getJoystickName: convert c_void_p to c_char_p before decoding

---

wpilib/wpilib/iterativerobotbase.py

Looks like this was a copypasta fail on our end.

IterativeRobotBase: Enable LiveWindow in test mode

---

wpilib/wpilib/i2c.py

Make differences between transaction() and writeBulk() more clear.

Add tip about writeBulk() to transaction() docs

---

wpilib/wpilib/_impl/main.py
wpilib/wpilib/driverstation.py

- Fix traceback handling to work under exception/no-exception situations
- Remove sys.excepthook handler as it doesn't add value (we already handle the main thread)
- Fixes #449

Fix driverstation error reporting

---

wpilib/wpilib/cameraserver.py

- Not complete, but good enough for now I suppose
- Fixes https://github.com/robotpy/robotpy-cscore/issues/25
@PeterJohnson @auscompgeek thoughts? Seems good enough to me.

Report cscore usage reporting data

---

hal-sim/hal_impl/functions.py
wpilib/wpilib/timedrobot.py

- Less threads is a good thing
- See https://github.com/wpilibsuite/allwpilib/pull/942
Tried it on a RoboRIO and it works as expected. Depends on https://github.com/robotpy/pyfrc/issues/94 to be fixed for it to work in sim/test.

TimedRobot now uses the HAL Notifier API directly

---

hal-sim/hal_impl/functions.py
wpilib/tests/spec_scanners/hal_scanner.py

* Fix string comparison in analog triggers
* Raise a descriptive error in unimplemented stubs

Fix up simulation HAL

---

.gittrack
devtools/exclude_commits
wpilib/wpilib/i2c.py

Update git source-track metadata

---

wpilib/wpilib/__init__.py
wpilib/wpilib/sensorutil.py

actually SensorBase was just renamed to this. it affects a bunch of files, so a full rename isn't happening here

add port of SensorUtil

---

devtools/exclude_commits
wpilib/wpilib/analogtriggeroutput.py
wpilib/wpilib/command/conditionalcommand.py
wpilib/wpilib/interfaces/controller.py
wpilib/wpilib/interfaces/generichid.py
wpilib/wpilib/interfaces/gyro.py
wpilib/wpilib/smartdashboard.py
wpilib/wpilib/timer.py
wpilib/wpilib/watchdog.py

update timer for 2019

---

hal-base/hal/functions.py
hal-roborio/hal_impl/distutils.py
hal-roborio/hal_impl/types.py
hal-sim/hal_impl/data.py
hal-sim/hal_impl/functions.py
hal-sim/hal_impl/serial_helpers.py
hal-sim/hal_impl/spi_helpers.py
hal-sim/hal_impl/types.py
wpilib/tests/spec_scanners/hal_scanner.py
wpilib/tests/test_powerdistributionpanel.py
wpilib/travis-requirements.txt
wpilib/wpilib/adxrs450_gyro.py
wpilib/wpilib/driverstation.py
wpilib/wpilib/powerdistributionpanel.py
wpilib/wpilib/spi.py

Didn't fix any of the underlying stuff, I'm sure the tests will fail.

HAL updates for 2019

---

.gittrack
wpilib/tests/test_watchdog.py
wpilib/wpilib/watchdog.py

Also fix a couple of logging-related format string bugs.

Update Watchdog to use a single thread

---

wpilib/tests/conftest.py
wpilib/tests/test_command.py
wpilib/tests/test_pidcontroller.py
wpilib/wpilib/pidbase.py
wpilib/wpilib/pidcontroller.py

update pidcontroller for 2019

---

wpilib/wpilib/_impl/main.py

- This is incredibly useful for certain types of debugging, and AFAIK
doesn't add any noticeable overhead, so we enable it by default
- Fixes #266

Enable faulthandler

---

.travis.yml

Bonus: Make the format-check job run in parallel too.
Closes: #562

Fix deploy in Travis CI config

---

wpilib/wpilib/command/subsystem.py
wpilib/wpilib/iterativerobotbase.py
wpilib/wpilib/samplerobot.py

Small tweak to the wording. "Overloading" is multiple functions with the same name but different signatures. "Overriding" is changing/providing the implementation of a baseclass method.

The OO terminology here is "override" -- not "overload".

---

hal-roborio/hal_impl/fndef.py

hal-roborio: Fix getting errno

---

wpilib/wpilib/__init__.py

Fixes PIDBase not showing in the docs.

wpilib: Expose PIDBase

---

wpilib/wpilib/driverstation.py
wpilib/wpilib/iterativerobotbase.py
wpilib/wpilib/robotbase.py
wpilib/wpilib/samplerobot.py

We experience a lot of lock contention/overhead when calling these functions, so it makes sense to combine them. Upstream request at https://github.com/wpilibsuite/allwpilib/issues/1620
These are important, but pretty sure I got it right.

Make determining robot mode more efficient

---

wpilib/wpilib/shuffleboard/camerawidget.py
wpilib/wpilib/shuffleboard/container.py

shuffleboard: Add method to add camera stream widget

---

.travis.yml

Remove Python 3.5 and add 3.8 to CI

---

hal-base/setup.py
hal-roborio/setup.py
hal-sim/setup.py
wpilib/setup.py

Remove Python 3.5 and add 3.7, 3.8 Trove classifiers

---

wpilib/setup.py

Continuation of #612
Based on #606

Change minimum required version to Python 3.6

---

gen/Color.yml
gen/Color8Bit.yml

Fix Color* constructor param names and add repr

---

gen/geometry/Pose2d.yml
gen/geometry/Rotation2d.yml
gen/geometry/Translation2d.yml
wpilib/src/rpy/geometryToString.h

Add repr for Pose2d and Translation2d

---

.github/workflows/dist.yml

Relates to robotpy/pyfrc#165
Sends pyfrc a webhook to update it's wpilib dependency to the latest version.

Ping pyfrc on successful publish

---

gen/geometry/Pose2d.yml
gen/geometry/Rotation2d.yml
gen/geometry/Translation2d.yml

Removes unnecessary intermediary lambdas.

Simplify geometry repr implementations

---

gen/DriverStation.yml
gen/RobotBase.yml
pyproject.toml
wpilib/src/rpy/ControlWord.cpp
wpilib/src/rpy/ControlWord.h
wpilib/src/rpy/DriverStation.cpp.inl
wpilib/src/rpy/RobotBase.cpp.inl

Also fixes the getControlState return type to be a typed tuple.

Deduplicate control word routines

---

gen/geometry/Pose2d.yml
gen/geometry/Transform2d.yml
gen/geometry/Translation2d.yml

@auscompgeek let's fight about this. I'll go first.
... you're a poopy head!

Add feet to Pose2d/Translation2d

---

gen/SendableChooserBase.yml

Hide SendableChooser instances atomic int

---

gen/drive/DifferentialDrive.yml

Here's to hoping I didn't screw up the Sphinx references!

Fix DifferentialDrive docs

---

gen/simulation/DifferentialDrivetrainSim.yml
gen/simulation/ElevatorSim.yml

Add getDistanceInches functions

---

gen/SmartDashboard.yml
pyproject.toml
tests/test_wpilib.py
wpilib/src/rpy/SmartDashboardData.cpp
wpilib/src/rpy/SmartDashboardData.h

Keep a reference to Sendable objects when passed to SmartDashboard::putData

---

gen/drive/DifferentialDrive.yml

Fix DifferentialDrive code example rendering

---

gen/SmartDashboard.yml
wpilib/simulation/simulation.cpp
wpilib/src/rpy/SmartDashboardData.cpp
wpilib/src/rpy/SmartDashboardData.h

Depends on:
* https://github.com/wpilibsuite/allwpilib/pull/4007
* https://github.com/wpilibsuite/allwpilib/pull/4037

helpers to enable robot integration testing

---

gen/MotorControllerGroup.yml
tests/test_wpilib.py

Better error message when constructing a motor controller group
