hal-base/hal/functions.py

- Fixes #143
To test this, you can do the following:
```
git clone https://github.com/robotpy/robotpy-wpilib.git
cd robotpy-wpilib
git checkout hal-warning
```
On a linux/OSX system, or if you have MSYS installed on windows, you can run `devtools/build_and_install.sh`. If you don't have either of those, post a comment and I can write something up that will get you going.

Don't throw errors when HAL emits a warning

---

wpilib/wpilib/counter.py

Otherwise we run into errors when we try to ```free()```

Set upSource and downSource properties to None if not in use.

---

wpilib/tests/conftest.py
wpilib/tests/test_livewindow.py
wpilib/wpilib/adxl345_i2c.py
wpilib/wpilib/adxl345_spi.py
wpilib/wpilib/analogaccelerometer.py
wpilib/wpilib/analoginput.py
wpilib/wpilib/analogoutput.py
wpilib/wpilib/builtinaccelerometer.py
wpilib/wpilib/cantalon.py
wpilib/wpilib/digitalinput.py
wpilib/wpilib/doublesolenoid.py
wpilib/wpilib/encoder.py
wpilib/wpilib/geartooth.py
wpilib/wpilib/gyro.py
wpilib/wpilib/jaguar.py
wpilib/wpilib/livewindow.py
wpilib/wpilib/relay.py
wpilib/wpilib/servo.py
wpilib/wpilib/solenoid.py
wpilib/wpilib/talon.py
wpilib/wpilib/talonsrx.py
wpilib/wpilib/ultrasonic.py
wpilib/wpilib/victor.py
wpilib/wpilib/victorsp.py

Added a try/except to catch any exceptions thrown by device's `.startLiveWindowMode()` hook.
Also added a `LiveView.removeComponent()` method, and now call it from the `free()` method of every device that has a `LiveWindow.addDevice()` in it's `__init__()`.
This fixes #148

LiveWindow work: Fix DS thread crashing from exceptions thrown by LV device hooks.

---

wpilib/wpilib/pidcontroller.py

Deque used for tolerance buffer was not being correctly resized
due to syntax error.

PIDController deque resizing fixed.

---

wpilib/wpilib/command/scheduler.py

StringArray and NumberArray objects do not have an "add" method, but they do have "append" which appears to have the desired behavior.

Use "append" for NetworkTable Arrays

---

wpilib/wpilib/preferences.py

Based on line 85 and by comparison with the _write method, this appears to be a typo.

Fix internal "read" method name

---

wpilib/wpilib/preferences.py

The partition method returns a 3-tuple, so we need three variables to unpack it.

Fix ValueError

---

wpilib/wpilib/command/__init__.py
wpilib/wpilib/command/command.py
wpilib/wpilib/command/instantcommand.py
wpilib/wpilib/command/printcommand.py
wpilib/wpilib/command/startcommand.py
wpilib/wpilib/command/timedcommand.py
wpilib/wpilib/command/waitcommand.py
wpilib/wpilib/command/waitforchildren.py
wpilib/wpilib/command/waituntilcommand.py

Since we were the ones that got [these changes](https://github.com/wpilibsuite/allwpilib/pull/238) merged into WPILib, it seemed like our responsibility to handle the porting for Python. We are not a beta team, so we can't test with the new HAL, but the code works with last year's firmware and there are no low-level changes.

Update command classes for 2017

---

devtools/convert_javadoc.html

Didnt use any fancy regex stuff, but the fix works.

Fix javadoc converter to exclude argument types

---

wpilib/wpilib/__init__.py
wpilib/wpilib/canjaguar.py
wpilib/wpilib/cantalon.py

Placeholders for the CANTalon/CANJaguar classes that were removed. Both should throw an error when created. #212

Add CANTalon and CANJaguar placeholders

---

wpilib/wpilib/command/scheduler.py

Fixes the ImportError when trying to use the Scheduler, and changes StringArray and NumberArray to Python lists.

Update NetworkTables usages in Scheduler

---

wpilib/wpilib/command/conditionalcommand.py

Call the parent's constructor before attempting to set requires.

Fixes Conditional Command

---

wpilib/wpilib/command/scheduler.py

When setting a Number array value, it is interpreted as a tuple, not a list. This line used a list method on the tuple, causing an attribute error when cancelling a command. This updated version will work whether the value is a tuple or a list.

Fix Attribute Error

---

hal-sim/hal_impl/data.py
wpilib/wpilib/driverstation.py

also, add a slot for joystick name

getJoystickName shouldn't bomb out

---

docs/regen.py
wpilib/wpilib/buttons/joystickbutton.py
wpilib/wpilib/buttons/networkbutton.py
wpilib/wpilib/interfaces/potentiometer.py

This causes the docs to skip generating documentation for classes that are not
documented.  This is intended to skip the CANTalon and CANJaguar stubs that were
added in 2017 to direct users to the relevant packages (or lack thereof).
This also documents a couple of classes in the buttons and interfaces packages
that were meant to be documented, but weren't.
I have verified that there are no other classes that are undocumented using the
following snippet:
```python
[x for package in [wpilib, wpilib.buttons, wpilib.command, wpilib.interfaces]
for x in vars(package).values() if inspect.isclass(x) and not x.__doc__]
```
Fixes: #268

docs: Skip undocumented classes

---

devtools/convert_javadoc.html

This makes convert_javadoc.html intelligent enough to be able to Java types to Python type hints.
Some minor handwaving was used in determining some of the matching types, based on their usage.  This should cover pretty much all of Java's types used in WPILib.

convert_javadoc: Convert types to annotations

---

wpilib/wpilib/lineardigitalfilter.py

Upstream changed their CircularBuffer helper class to be more idiomatic, but we just use collections.deque.
(Maybe we want to reconsider this? Their CircularBuffer is array-backed and doesn't shuffle elements around, so it'd be more efficient than a doubly-linked list, right?)

Validate LinearDigitalFilter

---

wpilib/wpilib/adxrs450_gyro.py
wpilib/wpilib/analoggyro.py

This ensures that these gyros work as a PIDSource as expected.
(Found this using lgtm.com. A fair few false positives there, but hey I found these.)

Add missing call to super().__init__() in gyros

---

docs/conf.py
docs/requirements.txt

We're trying to move towards using type hints to aid tools like mypy.
This makes the type hints not look rubbish in the docs.

docs: Use sphinx-autodoc-typehints

---

docs/requirements.txt

We weren't installing the wpilib package on RTD.  This prevented the
generation of the version file, which in turn led to the docs not
showing the version as 'master' instead of the actual version.

Fix version display on Read the Docs

---

hal-roborio/setup.py
hal-sim/setup.py
wpilib/wpilib/_impl/main.py

This should fix #303.
This adds some fairly simple checks to make sure that the `robotpy-hal-sim` package isn't accidentally installed onto an actual RoboRIO. This also adds logging to `wpilib.run` that indicates when a simulated HAL is in use, and warns whenever a simulated HAL is being used on a RoboRIO.

Add checks to ensure simulation HAL is not installed on RoboRIO

---

wpilib/wpilib/sensorbase.py

Let these calls go up to SendableBase.free().
Upstream doesn't have a free method here anyway.

Remove SensorBase.free() method

---

wpilib/tests/spec_scanners/wpilib_scanner.py

* Update the WPILibJ tree path.
* Use `inspect.getfullargspec()` instead of the deprecated `inspect.getargspec()`, which cannot deal with Python 3 syntax.

Fix WPILib spec scanner

---

docs/regen.py

Now that we have all the LiveWindow/Sendable changes for this year,
these boilerplate methods no longer exist.  Stop excluding them so they
show up in the docs for the deprecated LiveWindowSendable and
NamedSendable stubs.

docs: Delete LiveWindowSendable exclude-members

---

wpilib/setup.py
wpilib/travis-requirements.txt

Also reorder the requirements.txt so that pynetworktables is actually
installed first.  This eliminates the need for the ROBOTPY_NO_DEPS
environment variable for wpilib's setup.py.

Bump pynetworktables dependency

---

wpilib/wpilib/robotbase.py

Currently a new warning is caused whenever the `Robots shouldn't quit...` error is reported. In wpilibj the `printTrace` argument is `false` in all calls, so I've updated it to be that way here as well.

Provide printTrace parameter in calls to DriverStation.reportWarning/Error

---

hal-base/hal/functions.py

This should fix that error that @twinters007 was encountering. Hard to tell when it's an unreadable copy-paste from the DS log though.
Closes: #421

Fix _freeMatchInfo TypeError on roboRIO

---

wpilib/wpilib/iterativerobotbase.py

Hi im Evan from Thunderdogs team 5613, we found a deprecation problem in iterativerobotbase.

replacing warn with warning due to deprecation in pytest

---

wpilib/wpilib/samplerobot.py

Given that WPILib mainly marked SampleRobot as deprecated to give teams
a large warning in their IDEs and at compile time, we have decided that
this is probably a bad idea until we come up with a nicer solution.
This also restores the large orange warning box in the docs.

SampleRobot: Remove runtime warning

---

wpilib/wpilib/driverstation.py

If the game specific message or the event name are queried before the
driver station connects to the roboRIO, these will be null.
In this scenario, we should return None as is rather than trying to
decode it (which would obviously fail with an AttributeError).

DriverStation: Check None-ness before decode

---

hal-base/hal/functions.py

This should allow all the appropriate OSError subclasses to be returned,
and preserve the original errno in error messages.

hal: Pass errno to OSError constructor

---

wpilib/wpilib/driverstation.py

Let Shuffleboard's powerup field widget work.

DriverStation: Send a dummy control word over NT

---

hal-roborio/hal_impl/types.py
hal-sim/hal_impl/types.py
wpilib/wpilib/driverstation.py

This allows Shuffleboard's basic FMS info widget to correctly report the robot status.
Whilst I haven't had a chance to test this on a roboRIO, the ctypes magic works correctly in simulation as well (it was actually the original simulation implementation too, but I decided against using in simulation).
I'm still unsure whether this is actually the approach we should take in simulation, or whether we should actually use the ctypes hackery in simulation too. (I think we do want to use the ctypes magic on the roboRIO though, as I believe it will be faster, but again I haven't checked that.)

DriverStation: Send actual control word over NT

---

hal-base/hal/functions.py
hal-sim/hal_impl/data.py
wpilib/tests/test_driverstation.py
wpilib/wpilib/driverstation.py

Since DriverStation now constantly sends match info to the dashboard
over NetworkTables, having to decode multiple times is wasteful.
This is the same approach WPILibJ uses anyhow.

Move decoding strings in match info to HAL

---

.gittrack
devtools/exclude_commits
wpilib/wpilib/analoginput.py
wpilib/wpilib/analogoutput.py

- Ignore the Java simulation API stuff
- Bump gittrack to track one commit ahead of v2019.1.1-beta-1.

Update git-source-track metadata for beta

---

wpilib/wpilib/iterativerobot.py

This gives a more useful source line with the warning message.

IterativeRobot: Move DeprecationWarning to subclass init

---

.gittrack
wpilib/wpilib/watchdog.py

Resetting the flag should only occur in enable() and reset().
IterativeRobotBase needs the flag to remain set to print epochs after
disabling the Watchdog.

Fix Watchdog resetting expiration flag on disable

---

wpilib/wpilib/sendablechooser.py

- Looks like an improper translation from Java
- If it does throw, it would be good to be aware of it?

Don't swallow exceptions in sendable chooser

---

wpilib/tests/test_sendablechooser.py
wpilib/wpilib/sendablebuilder.py
wpilib/wpilib/sendablechooser.py

- Adds python-specific API to SendableBuilder
- Fixes https://github.com/robotpy/pyfrc/issues/155
- Fixes https://github.com/robotpy/robotpy-wpilib-utilities/issues/129

Allow sendable chooser to respond to local NT changes

---

wpilib/wpilib/watchdog.py

Avoid looking up a global variable in a hot loop.

Watchdog: Get logger object before printEpochs loop

---

hal-base/hal/functions.py

Without this:
```
admin@roboRIO-2423-FRC:~# python3 -m timeit -s 'import hal' 'hal.getFPGATime()'
10000 loops, best of 5: 29 usec per loop
```
With this:
```
admin@roboRIO-2423-FRC:~# python3 -m timeit -s 'import hal' 'hal.getFPGATime()'
10000 loops, best of 5: 27.6 usec per loop
```

Micro-optimization for _STATUSFUNC

---

hal-sim/hal_impl/data.py

Limiting the number of encoders to the number of labeled DIO ports on the RIO divided by 2 causes failure when tests run using hal-sim
I believe the max number of encoders is number of DIO divided by 2, so this commit allows up to 13 encoders before an error is raised.

update max number of encoders available in hal-sim

---

hal-sim/hal_impl/functions.py
wpilib/tests/test_counter.py
wpilib/tests/test_i2c.py
wpilib/tests/test_pwm.py
wpilib/tests/test_relay.py
wpilib/tests/test_solenoid.py
wpilib/tests/test_spi.py
wpilib/wpilib/analoginput.py
wpilib/wpilib/analogoutput.py
wpilib/wpilib/analogtrigger.py
wpilib/wpilib/counter.py
wpilib/wpilib/digitaloutput.py
wpilib/wpilib/encoder.py
wpilib/wpilib/i2c.py
wpilib/wpilib/interruptablesensorbase.py
wpilib/wpilib/pwm.py
wpilib/wpilib/relay.py
wpilib/wpilib/serialport.py
wpilib/wpilib/solenoid.py
wpilib/wpilib/spi.py

- They don't provide any value, since an error will be raised by the HAL if an invalid handle is used

Optimization: remove property indirection for HAL handles

---

wpilib/wpilib/sendablechooser.py

Per @auscompgeek 's indirect suggestion, this should help improve NT performance also.

Only make sendable chooser local notifications happen in simulation

---

wpilib/tests/test_driverstation.py
wpilib/wpilib/driverstation.py

This could definitely cause some performance issues -- though it appears there's a cache down in HAL too stopping it from going out to netcomm, so it might not be a huge improvement.

Control word cache should expire every 50ms, not every 50us

---

wpilib/src/rpy/DriverStation.cpp.inl
wpilib/src/rpy/RobotBase.cpp.inl

`py::bool_` as the return type confuses all sorts of tooling.

Fix bool_ in custom control word method signatures

---

gen/geometry/Pose2d.yml
gen/geometry/Rotation2d.yml
gen/geometry/Transform2d.yml
gen/geometry/Translation2d.yml
gen/geometry/Twist2d.yml

These are value types which are never passed around through shared_ptr.
Also reduce the redundancy of the signature for Rotation2d.fromDegrees.

Simplify geometry objects

---

gen/controller/SimpleMotorFeedforward.yml
wpilib/controller/__init__.py

As it turns out, this is used by DifferentialDriveVoltageConstraint.
(It doesn't take SimpleMotorFeedforwardFeet. I checked.)

Document SimpleMotorFeedforwardMeters

---

gen/trajectory/TrapezoidProfile.yml

Note that the TrapezoidProfile ctor default initial still shows up with the object repr rather than the State repr. I presume this is due to the ctor being defined before the State repr is defined.

Make TrapezoidProfile actually usable

---

wpilib/src/rpy/geometryToString.h

It's already obvious that each part is the translation and rotation component.
This matches up closer with the Java version.

Simplify Pose2d repr

---

gen/kinematics/ChassisSpeeds.yml
gen/kinematics/DifferentialDriveWheelSpeeds.yml
gen/kinematics/SwerveModuleState.yml
wpilib/src/rpy/geometryToString.h

[From the Python documentation for `repr()`](https://docs.python.org/3/library/functions.html#repr):
> For many types, this function makes an attempt to return a string that would yield an object with the same value when passed to `eval()`, otherwise the representation is a string enclosed in angle brackets [...]
This reverts the geometry `__repr__` and fixes the kinematics `__repr__` implementations to adhere to the expected behaviour of `repr()`.

Fix geometry/kinematics reprs

---

docs/requirements.txt
gen/SendableChooser.yml
tests/test_wpilib.py

Demonstration of prior error:
```
def test_sendable_chooser():
chooser = wpilib.SendableChooser()
>       assert chooser.getSelected() is None
E       TypeError: Unable to convert function return value to a Python type! The signature was
E               (self: wpilib._wpilib.SendableChooser) -> object
```

Fix empty sendable chooser

---

gen/drive/DifferentialDrive.yml

The current `DifferentialDrive` docs examples do not work since `DifferentialDrive` is located in the `wpilib.drive` module.
I also added the two separate imports that are needed : the second is often forgotten by new Python students.

Fix DifferentialDrive docs examples

---

wpilib/_impl/start.py

- This isn't quite right, something is handling the signal and the CTRL-C isn't getting processed somehow

Prevent abort() on CTRL-C on sim on Linux

---

wpilib/__init__.py
wpilib/_impl/main.py
wpilib/deployinfo.py

Not quite sure if I like the naming or placement of these. Open for bikeshedding. Currently looks like this:
```
02:17:53:468 INFO    : deploy-info         : virtuald@hostname at 2022-03-04T02:04:09
02:17:53:468 INFO    : deploy-info         : - git info: fa1331a-dirty (branch=main)
```

Display deploy.json data at robot startup

---

gen/DataLogManager.yml
tests/test_datalogmanager.py

```pytb
Traceback (most recent call last):
File "~/.local/share/virtualenvs/rpy/lib/python3.10/site-packages/wpilib/_impl/start.py", line 131, in _start
self.robot.startCompetition()
File "~/dev/frc/robotpy/robotpy-wpilib-utilities/magicbot/magicrobot.py", line 355, in startCompetition
self.robotInit()
File "~/dev/frc/robotpy/robotpy-wpilib-utilities/magicbot/magicrobot.py", line 98, in robotInit
self.createObjects()
File "~/dev/frc/thedropbears/pyrapidreact/robot.py", line 47, in createObjects
self.data_log = wpilib.DataLogManager.getLog()
RuntimeError: return_value_policy = copy, but type is non-copyable! (compile in debug mode for details)

Fix DataLogManager.getLog() trying to copy

---

wpilib/_impl/start.py

- Fallback to wpilib if needed
Since we're going to pin versions, this seems to make sense.

Write the robotpy-meta version to /tmp/frc_versions/FRC_Lib_Version.ini
